apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a48yyed2h-nodejs
  janus-idp.io/tekton: a48yyed2h-nodejs
  backstage.io/kubernetes-id: a48yyed2h-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a48yyed2h-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
